from pathlib import Path
import base64,json
p=Path('sprites/avatar-lab')
meta=json.loads((p/'sample-sheet.json').read_text())
def data(f):return 'data:image/png;base64,'+base64.b64encode(Path(f).read_bytes()).decode()
assets={l['name']:data(p/(l['name']+'.png')) for l in meta['meta']['layers']}
manifest={'version':2,'frameSize':[256,256],'sheetSize':[meta['meta']['size']['w'],meta['meta']['size']['h']],'columns':6,'origin':[128,171],'headAnchor':[130,100],'handAnchor':[147,141],'actions':meta['meta']['frameTags'],'durations':[v['duration'] for v in meta['frames'].values()], 'layers':list(assets),'note':'Hero School native format; not an MSW PSD import file.'}
(p/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
html='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>공통 아바타 애니메이션 테스트</title><style>
*{box-sizing:border-box}body{margin:0;background:#151923;color:#e9e4d7;font:14px system-ui}main{max-width:1100px;margin:auto;padding:20px}h1{font-size:23px;margin:0 0 8px}p{color:#b7bdcc;line-height:1.6}button,select,a.dl{font:inherit;color:#eee;background:#303b50;border:1px solid #59657b;border-radius:6px;padding:9px;cursor:pointer}button:focus-visible,select:focus-visible{outline:2px solid #f3ca7c}.grid{display:grid;grid-template-columns:1fr 280px;gap:16px}.card{background:#202735;border:1px solid #455066;border-radius:12px;padding:16px}.stages{display:flex;justify-content:center;align-items:end;gap:16px;flex-wrap:wrap}.stage{height:310px;width:300px;display:flex;align-items:center;justify-content:center;background:repeating-conic-gradient(#272e3a 0% 25%,#303847 0% 50%) 0/24px 24px;border-radius:8px;overflow:hidden}canvas{flex:none;image-rendering:pixelated;width:512px;height:512px;max-width:none}figure{margin:0;text-align:center}figcaption{color:#c4cbd7;padding:8px}.ref{width:256px;height:256px;image-rendering:pixelated}.controls{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0;align-items:center}.parts{display:grid;gap:10px}.parts label{background:#30394b;padding:9px;border-radius:5px}.parts input{accent-color:#ddba76;margin-right:9px}input[type=range]{width:180px}#sheet{width:100%;image-rendering:pixelated;background:#303847}a.dl{display:inline-block;text-decoration:none;font-size:12px}.badge{color:#eccb87}.foot{font-size:12px} @media(max-width:700px){main{padding:12px}.grid{grid-template-columns:1fr}.stage{width:270px}.ref{width:180px;height:180px}.parts{grid-template-columns:1fr 1fr}}
</style><main><h1>애니메이션 테스트</h1><p>거너 비율을 참고한 공통 베이스 샘플입니다. 부위를 켜고 끄면서 모든 동작에서 겹침과 위치를 확인하세요.</p><div class="grid"><section class="card"><div class="stages"><figure><div class="stage"><canvas id="avatar" width="256" height="256"></canvas></div><figcaption>공통 베이스 · <span id="counter"></span></figcaption></figure><figure><img class="ref" src="__REF__"><figcaption>현재 거너 · 비율 참고</figcaption></figure></div><div class="controls"><select id="action" aria-label="동작"><option value="idle">대기</option><option value="attack">공격</option><option value="hit">피격</option><option value="down">쓰러짐</option><option value="win">승리</option><option value="swing_one">한손 휘두르기</option><option value="swing_two">양손 휘두르기</option><option value="shoot_gun">총쏘기</option><option value="shoot_bow">활쏘기</option><option value="lie">눕기</option></select><button id="play">일시정지</button><button id="step">다음 프레임</button><select id="speed" aria-label="속도"><option value="0.5">0.5배</option><option selected value="1">1배</option><option value="2">2배</option></select><label><input type="checkbox" id="flip">좌우 반전</label></div><div class="controls"><label>프레임 <input type="range" id="frame" min="0" max="2" value="0"></label><label>확대 <select id="zoom"><option value="1">1배</option><option selected value="2">2배</option><option value="3">3배</option></select></label></div><p id="status" role="status">시트를 불러오는 중…</p></section><aside class="card"><h2>착용 레이어</h2><div class="controls"><button id="base">기본 몸체</button><button id="all">샘플 전체 착용</button></div><div id="parts" class="parts"></div><p class="foot">공통 머리·몸·팔은 항상 유지됩니다. 앞뒤로 나뉜 헤어는 함께 전환합니다. 의상은 구조 확인용 시험 디자인입니다.</p></aside></div><details class="card" style="margin-top:16px"><summary>통합 시트 · 제작 파일</summary><p>256 × 256 셀 · 36프레임 · 10동작 · 발 기준점 (128, 171). 동작은 태그로 구분합니다.</p><div class="controls"><a class="dl" download="common-avatar-sample.aseprite" href="__ASE__">Aseprite 원본</a><a class="dl" download="sample-sheet.png" href="__SHEET__">통합 PNG</a><a class="dl" download="manifest.json" href="__JSON__">프레임 규격</a></div><img id="sheet" src="__SHEET__"></details></main><script>
const manifest=__MANIFEST__,sources=__ASSETS__;
const groups=[['face','눈 + 입',['face']],['cape','망토',['cape_back']],['pants','하의',['pants']],['top','상의',['top']],['gloves','장갑',['gloves']],['shoes','신발',['shoes']],['hair','헤어',['hair_back','hair_front']],['hat','모자',['hat']]];
const enabled=new Set(groups.map(x=>x[0])),images={};let playing=true,index=0,last=0,loaded=false;
const $=id=>document.getElementById(id),ctx=$('avatar').getContext('2d');ctx.imageSmoothingEnabled=false;
$('parts').innerHTML=groups.map(([key,label])=>`<label><input type="checkbox" data-part="${key}" checked>${label}</label>`).join('');
function tag(){return manifest.actions.find(a=>a.name===$('action').value)}
function draw(){if(!loaded)return;const t=tag(),f=t.from+index;ctx.clearRect(0,0,256,256);ctx.save();if($('flip').checked){ctx.translate(256,0);ctx.scale(-1,1)}for(const key of manifest.layers){const g=groups.find(g=>g[2].includes(key));if(g&&!enabled.has(g[0]))continue;ctx.drawImage(images[key],f%6*256,Math.floor(f/6)*256,256,256,0,0,256,256)}ctx.restore();$('frame').value=index;$('counter').textContent=`${index+1} / ${t.to-t.from+1}`;}
$('parts').onchange=e=>{const key=e.target.dataset.part;if(e.target.checked)enabled.add(key);else enabled.delete(key);draw()};
$('base').onclick=()=>{enabled.clear();$('parts').querySelectorAll('input').forEach(x=>x.checked=false);draw()};$('all').onclick=()=>{groups.forEach(g=>enabled.add(g[0]));$('parts').querySelectorAll('input').forEach(x=>x.checked=true);draw()};
$('action').onchange=()=>{index=0;last=performance.now();$('frame').max=tag().to-tag().from;draw()};
function setPlay(v){playing=v;$('play').textContent=v?'일시정지':'재생';last=performance.now()}
$('play').onclick=()=>setPlay(!playing);$('step').onclick=()=>{setPlay(false);index=(index+1)%(tag().to-tag().from+1);draw()};$('frame').oninput=()=>{setPlay(false);index=+$('frame').value;draw()};$('flip').onchange=draw;$('zoom').onchange=()=>{const n=256*+$('zoom').value;$('avatar').style.width=n+'px';$('avatar').style.height=n+'px'};
Promise.all(Object.entries(sources).map(([key,url])=>new Promise((resolve,reject)=>{const im=new Image;im.onload=()=>{images[key]=im;resolve()};im.onerror=reject;im.src=url}))).then(()=>{loaded=true;$('status').textContent='모든 레이어 준비 완료';draw()}).catch(()=>{$('status').textContent='시트를 불러오지 못했습니다. 다시 열어 주세요.'});
function tick(now){if(loaded&&playing&&now-last>=manifest.durations[tag().from+index]/+$('speed').value){index=(index+1)%(tag().to-tag().from+1);last=now;draw()}requestAnimationFrame(tick)}requestAnimationFrame(tick);
</script></html>'''
repl={'__REF__':data('sprites/frames-v3/gunner/idle-00.png'),'__ASE__':'data:application/octet-stream;base64,'+base64.b64encode((p/'common-avatar-sample.aseprite').read_bytes()).decode(),'__SHEET__':data(p/'sample-sheet.png'),'__JSON__':'data:application/json;base64,'+base64.b64encode(json.dumps(manifest).encode()).decode(),'__MANIFEST__':json.dumps(manifest),'__ASSETS__':json.dumps(assets)}
for a,b in repl.items():html=html.replace(a,b)
(p/'preview.html').write_text(html,encoding='utf-8')
game=Path('game.html');s=game.read_text(encoding='utf-8');start='/* AVATAR_LAB_START */';end='/* AVATAR_LAB_END */'
js=start+'\nconst AVATAR_LAB_HTML='+json.dumps(html,ensure_ascii=False).replace(chr(60), chr(92)+'u003c').replace('<',r'<')+';\nfunction openAvatarLab(){showModal(`<div class="panel-h"><h2>애니메이션 테스트</h2><button class="btn" id="avatarLabClose">닫기</button></div><iframe id="avatarLabFrame" title="공통 아바타 테스트" style="width:100%;height:75dvh;border:0;border-radius:8px"></iframe>`);document.querySelector("#avatarLabFrame").closest(".modal").style.width="min(1180px,100%)";document.querySelector("#avatarLabFrame").srcdoc=AVATAR_LAB_HTML;document.querySelector("#avatarLabClose").onclick=closeModal;}\n'+end
if start in s:s=s[:s.index(start)]+js+s[s.index(end)+len(end):]
else:s=s.replace('function viewOpt(){',js+'\nfunction viewOpt(){')
if 'id="avatarLabOpen"' not in s:s=s.replace('return errPanel() + xferPanel() + `','return errPanel() + xferPanel() + `<section class="panel"><div class="optrow"><div class="optlab"><b>애니메이션 테스트</b><span>공통 몸체와 부위별 착용 레이어의 동작을 확인합니다.</span></div><button class="btn" id="avatarLabOpen">테스트 열기</button></div></section>',1)
if 'const labOpen = $("#avatarLabOpen")' not in s:s=s.replace('    const sl = $("#fxA");','    const labOpen = $("#avatarLabOpen"); if(labOpen) labOpen.onclick=openAvatarLab;\n    const sl = $("#fxA");',1)
game.write_text(s,encoding='utf-8');print('Packed sample and settings entry')
