const {chromium}=require('playwright'),assert=require('assert');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'}),p=await b.newPage({viewport:{width:1600,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:18765/ui/chronicle/preview.html');await p.waitForFunction(()=>document.querySelector('iframe').contentDocument?.querySelector('.chronicle'));const f=p.frames()[1];
const run=fn=>f.evaluate(fn);assert.equal(await f.locator('.handrow .card').count(),9);
await f.locator('.handrow .card').first().click();assert.equal(await run(()=>S.slots.filter(Boolean).length),1);await f.locator('.chron-entry').first().click();assert.equal(await run(()=>S.slots.filter(Boolean).length),0);
// Native drop path and return to hand.
await run(()=>{const card=document.querySelector('.handrow [data-card]'),dt=new DataTransfer();dt.setData('text/plain',card.dataset.card);document.querySelector('[data-slot="3"]').dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:dt}));});assert(await run(()=>!!S.slots[3]));await f.locator('#btnClearSlots').click();
// Pointer drag (same engine used on touch).
const src=await f.locator('.handrow .card').first().boundingBox(),dst=await f.locator('[data-slot="1"]').boundingBox();await p.mouse.move(src.x+src.width/2,src.y+40);await p.mouse.down();await p.mouse.move(dst.x+dst.width/2,dst.y+20,{steps:15});await p.mouse.up();assert(await run(()=>!!S.slots[1]));
await p.locator('#more').click();assert.equal(await f.locator('.chron-student').count(),15);await f.locator('[data-chron-page="1"]').click();assert.equal(await f.locator('.chron-student').count(),3);await f.locator('[data-chron-focus]').first().selectOption('rest');assert(await run(()=>S.students[15].focus==='rest'));await f.locator('[data-chron-page="-1"]').click();
await f.locator('#btnAuto').click();assert.equal(await run(()=>S.slots.filter(Boolean).length),5);assert(await f.locator('#btnWeek').isEnabled());
await f.locator('.chronicle').screenshot({path:'ui/chronicle/preview-desktop.png'});
await f.locator('[data-chron-nav="facil"]').click();assert.equal(await run(()=>UI.view),'facil');assert.equal(await f.locator('.chronicle').count(),0);await p.locator('#opt').click();await f.locator('#chronicleToggle').uncheck();assert.equal(await run(()=>JSON.parse(localStorage.getItem(PREF_KEY)).chronicleTest),false);await p.locator('#plan').click();assert.equal(await f.locator('.chronicle').count(),0);await p.locator('#opt').click();await f.locator('#chronicleToggle').check();await p.locator('#plan').click();
await p.setViewportSize({width:390,height:844});assert(await f.locator('.chronicle').evaluate(el=>el.scrollWidth<=el.clientWidth+2));await f.locator('.chronicle').screenshot({path:'ui/chronicle/preview-mobile.png'});
await p.setViewportSize({width:1600,height:1100});await run(()=>{S.students=S.students.slice(0,3);UI.chroniclePage=0;S.slots.forEach((c,i)=>{if(c)c.t='rest'});render()});await f.locator('#btnWeek').click();await p.waitForTimeout(650);assert(await f.locator('#modalRoot').evaluate(el=>el.textContent.length>0));if(await f.locator('#mpGo').count())await f.locator('#mpGo').click();await p.waitForTimeout(500);console.log('Modal:',(await f.locator('#modalRoot').textContent()).slice(0,100));assert.deepEqual(errors,[]);console.log('PASS: click, native/pointer drag, 18 students, focus, auto fill, navigation, preference persistence, mobile bounds, stamped advance');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
